### ISSUE TITLE
‘Open Changes’ shows wrong diff

### ISSUE THREAD

**Issue by vor0nwe** [koog1000/vscode-fossil#129] opened 2023-05-24 19:49 UTC
When clicking on a changed file in the ‘Source Control’ pane, a new editor opens, titled "filename.ext (Working Directory)", showing the file from the repository, side by side with the current file, and highlighting the differences.

When I commit the changes, the file disappears from the list of changed files in the ‘Source Control’ pane. 
When I subsequently make new changes in that same file, it reappears in that same place. So far so good. But now when I click on it, it does open an editor showing side-by-side, however it shows both the new _and_ the previous changes (which have now been committed, and therefore should not be visible).

It would appear that the plugin remembers the revision that was active when I first opened the workspace, and always bases its diffs on that, instead of comparing the local file in the Work Directory with the unchanged version from the repository (which is what `fossil diff` does — correctly).

**Comment by senyai** [comment] 2023-05-25 07:25
Thank you for your report. Afaict the plugin reports 'current' as the name of the check-in and the caching is happening on the vscode side. I will see if I can change 'current' to the checkout hash reported by `fossil status`. I will take a closer look in a week.

**Comment by senyai** [comment] 2023-05-26 17:51
@vor0nwe even though you described your steps pretty clearly, I'm not be able to reproduce the issue. Can you record a video or describe it step by step with more details?

**Comment by senyai** [comment] 2023-08-03 08:12
@vor0nwe I was looking into this issue and still not sure how it can happen. Do you remember by chance, did you make a change when vscode was focused?

**Comment by vor0nwe** [comment] 2023-08-26 10:52
@senyai I’m sorry I haven’t been able to respond earlier (nor can I go in depth now), but the problem still occurs, with multiple repos, and on nearly all my machines. If you can’t reproduce it, then I suspect it might be caused by one of the many other extensions I have installed. The repos I most work with are from work, and I’m not supposed to record their code, so I can’t share a video.

I will try to see if I can reproduce it with only the fossil extension activated whenever I work on that code base, which should be in the course of the next few weeks.

**Comment by pekeler** [comment] 2023-09-12 12:11
FYI: I have witnessed this problem as well, many times. Always having to close the file to reset the diff cache is annoying. I'll try to record a video soon.

**Comment by pekeler** [comment] 2023-09-15 21:18
Here's a recording. I've made some changes to a couple of files, viewed the diff (worked fine), committed, left all the tabs open, made a couple of new changes, and now the diff is broken because it shows my previous changes plus the latest changes together as if the previous commit didn't happen. Closing and reopening the diff tab doesn't help. I have to close the tab for the file itself to get the diff to work correctly.

https://github.com/koog1000/vscode-fossil/assets/42363/c3fc9c88-79cf-492a-94df-67c70e857ffe

**Comment by vor0nwe** [comment] 2023-09-16 10:02
Thank you for that, @pekeler! That’s exactly the same problem I have.
Sorry I haven’t been able to get back to you @senyai; life, uh, keeps getting in the way.

Here’s a list of extensions I’ve got installed, maybe one of those causes the problem? (They’re not all enabled, but I can’t seem to find an easy way to export or copy just the enabled extensions):

- 076923.python-image-preview-0.1.2
- activitywatch.aw-watcher-vscode-0.5.0
- af4jm.vscode-icalendar-1.0.1
- alefragnani.numbered-bookmarks-8.4.0
- alefragnani.pascal-9.6.0
- alefragnani.pascal-formatter-2.8.1
- alefragnani.separators-2.5.0
- alexcvzz.vscode-sqlite-0.14.1
- almenon.arepl-2.0.5
- analytic-signal.preview-pdf-1.0.0
- ansonyeung.pascal-language-basics-0.1.10
- azurite.azurite-3.26.0
- bmewburn.vscode-intelephense-client-1.9.5
- bmuskalla.vscode-tldr-1.0.0
- brapifra.phpserver-3.0.2
- ckolkman.vscode-postgres-1.4.3
- codemooseus.vscode-devtools-for-chrome-0.0.7
- compulim.compulim-vscode-closetag-1.2.0
- craigthomas.supersharp-0.1.4
- cymonk.sql-formatter-1.0.2
- danielsanmedium.dscodegpt-2.1.15
- danielsanmedium.dscodegpt-2.1.18
- davidanson.vscode-markdownlint-0.51.0
- dbaeumer.vscode-eslint-2.4.2
- ddzy.file-positioning-1.0.4
- donjayamanne.githistory-0.6.20
- dotjoshjohnson.xml-2.5.1
- eamodio.gitlens-14.2.1
- eamodio.gitlens-14.3.0
- emmanuelbeziat.vscode-great-icons-2.1.97
- emmanuelbeziat.vscode-great-icons-2.1.98
- eriklynd.json-tools-1.0.2
- file-icons.file-icons-1.1.0
- firefox-devtools.vscode-firefox-debug-2.9.8
- fireside21.cshtml-0.1.3
- formulahendry.auto-close-tag-0.5.14
- formulahendry.auto-rename-tag-0.1.10
- formulahendry.azure-storage-explorer-0.1.2
- formulahendry.code-runner-0.12.0
- fudge.auto-using-0.7.15
- fwcd.kotlin-0.2.31
- gebv.pikchr-0.1.1
- github.vscode-pull-request-github-0.70.0
- golang.go-0.39.1
- grapecity.gc-excelviewer-4.2.58
- hbenl.vscode-test-explorer-2.21.1
- hookyqr.minify-0.4.3
- igress.python-coding-conventions-0.0.4
- ijustdev.gitea-vscode-2.1.0
- jamesmaj.easy-icons-0.3.1
- jock.svg-1.5.3
- kelvin.vscode-sshfs-1.26.1
- kiteco.kite-0.147.0
- k--kato.docomment-1.0.0
- koog1000.fossil-0.3.2
- leighlondon.eml-0.4.0
- littlefoxteam.vscode-python-test-adapter-0.7.1
- logerfo.csharp-colors-0.2.1
- magicstack.magicpython-1.1.0
- mathiasfrohlich.kotlin-1.7.1
- mechatroner.rainbow-csv-3.7.0
- mechatroner.rainbow-csv-3.7.1
- mrcrowl.hg-1.9.0
- mrmlnc.vscode-apache-1.2.0
- ms-azuretools.vscode-azureresourcegroups-0.7.5
- ms-azuretools.vscode-azurestorage-0.15.3
- ms-azuretools.vscode-docker-1.26.0
- ms-dotnettools.csdevkit-0.3.21-win32-x64
- ms-dotnettools.csdevkit-0.4.10-win32-x64
- ms-dotnettools.csharp-2.0.376-win32-x64
- ms-dotnettools.csharp-2.1.2-win32-x64
- ms-dotnettools.dotnet-maui-0.2.13-win32-x64
- ms-dotnettools.dotnet-maui-0.3.22-win32-x64
- ms-dotnettools.vscode-dotnet-runtime-1.7.0
- ms-dotnettools.vscode-dotnet-runtime-1.7.3
- ms-dotnettools.vscodeintellicode-csharp-0.1.26-win32-x64
- ms-edgedevtools.vscode-edge-devtools-2.1.3
- msjsdiag.debugger-for-edge-1.0.15
- ms-mssql.data-workspace-vscode-0.5.0
- ms-mssql.mssql-1.20.1
- ms-mssql.sql-bindings-vscode-0.4.0
- ms-mssql.sql-database-projects-vscode-1.2.0
- ms-python.isort-2023.10.1
- ms-python.python-2023.14.0
- ms-python.vscode-pylance-2023.8.30
- ms-python.vscode-pylance-2023.9.10
- ms-toolsai.jupyter-2023.7.1002162226-win32-x64
- ms-toolsai.jupyter-keymap-1.1.2
- ms-toolsai.jupyter-renderers-1.0.17
- ms-toolsai.vscode-jupyter-cell-tags-0.1.8
- ms-toolsai.vscode-jupyter-slideshow-0.1.5
- ms-vscode.azure-account-0.11.5
- ms-vscode.azurecli-0.5.0
- ms-vscode.cmake-tools-1.15.31
- ms-vscode.cpptools-1.17.3-win32-x64
- ms-vscode.cpptools-1.17.5-win32-x64
- ms-vscode.cpptools-extension-pack-1.3.0
- ms-vscode.cpptools-themes-2.0.0
- ms-vscode.hexeditor-1.9.12
- ms-vscode.live-server-0.4.9
- ms-vscode.mono-debug-0.16.3
- ms-vscode.notepadplusplus-keybindings-1.0.7
- ms-vscode.powershell-2023.6.0
- ms-vscode.remote-explorer-0.4.1
- ms-vscode.remote-server-1.4.2
- ms-vscode.remote-server-1.4.3
- ms-vscode.test-adapter-converter-0.1.8
- ms-vscode-remote.remote-containers-0.304.0
- ms-vscode-remote.remote-containers-0.309.0
- ms-vscode-remote.remote-ssh-0.102.0
- ms-vscode-remote.remote-ssh-edit-0.86.0
- ms-vscode-remote.remote-wsl-0.81.0
- ms-vscode-remote.remote-wsl-0.81.3
- ms-vscode-remote.vscode-remote-extensionpack-0.24.0
- mtxr.sqltools-0.28.0
- mtxr.sqltools-driver-sqlite-0.5.0
- nidu.copy-json-path-0.3.0
- njpwerner.autodocstring-0.6.1
- njqdev.vscode-python-typehint-1.5.1
- octref.vscode-json-transform-0.1.2
- pdconsec.vscode-print-0.11.15
- pkief.material-icon-theme-4.29.0
- pkief.material-icon-theme-4.30.1
- pmiossec.vscode-gitextensions-1.3.1
- pranthiks.sendmail-1.0.0
- prateekmahendrakar.prettyxml-3.5.0
- redhat.vscode-xml-0.26.1-win32-x64
- redhat.vscode-yaml-1.14.0
- remcoros.startanyshell-0.3.1
- riussi.code-stats-vscode-1.0.18
- roadsidejesus.csharp-helper-0.0.14
- rogalmic.bash-debug-0.3.9
- rogalmic.vscode-xml-complete-0.3.0
- ryu1kn.partial-diff-1.4.3
- searking.preview-vscode-2.2.5
- serkonda7.vscode-vba-0.9.1
- shardulm94.trailing-spaces-0.4.1
- shd101wyy.markdown-preview-enhanced-0.6.8
- shd101wyy.markdown-preview-enhanced-0.7.8
- spadin.remote-x11-ssh-1.5.0
- sunjw.jstool-1.2307.1
- sunjw.jstool-1.2308.0
- teamsdevapp.ms-teams-vscode-extension-5.0.1
- tobysmith568.run-in-powershell-1.2.0
- tomoki1207.pdf-1.2.2
- twxs.cmake-0.0.17
- vincaslt.highlight-matching-tag-0.11.0
- vscode-icons-team.vscode-icons-12.5.0
- wayou.vscode-todo-highlight-1.0.5
- weijunyu.vscode-json-path-2.4.0
- wilsonwong.caniuse-query-0.0.1
- wivuu.dotnetscriptr-0.2.4
- wosi.omnipascal-0.19.0
- xdebug.php-debug-1.33.0
- yuenm18.ooxml-viewer-2.0.0

**Comment by senyai** [comment] 2023-09-19 10:17
I'm still confused about how it can happen. I can see that other scm extensions (git, hg) moved from `TextDocumentContentProvider` to `FileSystemProvider` to provide file content, maybe it is related. @pekeler thanks for the clip, I believe I need the full story there with commits and everything, as I can't reproduce it.

My plan is to release 0.4.0 today and release 0.4.1 with `FileSystemProvider` in a week.

**Comment by senyai** [comment] 2023-09-24 19:47
Can you guys try 0.5.1 preview version (vscode only)? I moved from `TextDocumentContentProvider` to `FileSystemProvider`, but something tells me that's not gonna fix this issue. And if this preview version doesn't fix it, I need more info on what to do to reproduce this issue locally.

**Comment by vor0nwe** [comment] 2023-11-08 21:04
I finally got round to testing it; and I’m glad to report that the issue appears to be fixed, at least in version 0.5.4! Thanks a lot, @senyai!

@pekeler does it now work for you too?

**Closed** 2023-11-10 19:56 UTC
