### ISSUE TITLE
Fossil Request?

### ISSUE THREAD

**Issue by pekeler** [koog1000/vscode-fossil#15] opened 2019-10-13 22:29 UTC
I'm suddenly seeing "Fossil Request" editor tabs popping up in VSCode after saving changes to any file. What's going on here?
<img width="567" alt="ss" src="https://user-images.githubusercontent.com/42363/66723455-93cd4b80-edd6-11e9-9ff3-d99ed407e83d.png">

**Comment by pekeler** [comment] 2019-10-13 22:33
I've had this behavior with 0.0.10. Just upgraded to 0.0.14 and seeing the same. These new tabs are taking the focus, so it's quite disruptive.

**Comment by pekeler** [comment] 2019-10-13 22:55
I downgraded VSCode back to 1.39.0 and now the problem is gone. Perhaps something related to https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22September+2019+Recovery%22+is%3Aclosed

**Comment by koog1000** [comment] 2019-10-13 23:16
Hmmm, I'm using 1.39.1 and I've been working on a different project in VSCode all weekend and haven't seen that issue.

Basically, the extension thinks fossil is asking for user input. The only time this happens is if any fossil command output has a line ending with `: ` or `? ` (note the spaces as well). I don't believe this would be influenced by the version of VSCode unless they are piping other data through the fossil stdout stream, which would be weird.

I suppose this could happen if you files that contain those endings. Is that the case?

**Comment by koog1000** [comment] 2019-10-14 04:59
What happens if you type `fossil cat <myfile>` on the command line? Does fossil correctly cat the file contents?

I believe the extension will cat the contents of any file that you have open and in focus. You can force a `fossil cat` by [viewing the file diff from the scm explorer.](https://github.com/koog1000/vscode-fossil#view-file-changes) 

Just so I understand, your original problem went away but now you have the problem that it will not cat the file was causing issues before?

**Comment by pekeler** [comment] 2019-10-14 05:10
Yes, doing a `fossil cat` from the cmd-line correctly cats the full file.

Even opening the diff doesn't do the cat any more. It does show the correct diff, though. Could it be cached somewhere?

I just restarted VSCode, and now it does the cat again and the problem is back.

OK, so I added some characters to the top of this file, committed it, and now the problem is gone. So it smells like a buffer size issue for `fossil cat` to me - if a colon is right at the end of that buffer, it's triggering the issue.

**Comment by koog1000** [comment] 2019-10-14 05:32
Yes I was leading in that direction, but I can't find anything that states what the limit is. It's definitely not a limit placed by the extension, my guess is that has to do with how Node handles the stdout pipe for a child process.

Getting this deep into VSCode\Node implementation is well over my head, this is my first and only project working with it. 

If you have any insights or clever ways to prevent this from happening to other people, please let me know.

**Comment by koog1000** [comment] 2019-10-14 05:34
By chance, you mentioned earlier that made two changes to fossil global settings, what were those changes?

**Comment by pekeler** [comment] 2019-10-14 05:39
I set the binary-glob and updated the ignore-glob. Neither of which would include my problematic file.

**Comment by pekeler** [comment] 2019-10-14 05:40
Create a new file test.txt whose entire content is 8,200 colons. Check it in. Then make an edit to that file to reproduce the problem.

Instead of just checking the output for `:` and `?`, would it make sense to only look for those if the child process didn't terminate, i.e. is waiting for input?

**Comment by koog1000** [comment] 2019-10-14 06:02
Its easier to reproduce than that. Any file that ends with `:` or `?` would throw the error. 

Looking for stdout ending with `:` or `?` **is** my way of checking to see if the process is waiting for input. I suppose it must be possible to check if the [`exit`](https://nodejs.org/api/child_process.html#child_process_event_exit) event has been thrown. I'm already grabbing the exit code at that time so I could set some other flag that could be checked in conjunction with the `:` or `?`. 

But I think doing that will not fix the problem you are seeing, because the `fossil cat` command was in the middle of streaming the file contents, hence the process would still be open when the `:` came through.

**Comment by pekeler** [comment] 2019-10-14 23:26
> > Create a new file test.txt whose entire content is 8,200 colons. Check it in. Then make an edit to that file to reproduce the problem.

> Its easier to reproduce than that. Any file that ends with : or ? would throw the error.

The file has 8,200 colons and then ends on something else, such as "abc". To reproduce the buffer-like error.

**Comment by koog1000** [comment] 2019-10-19 16:19
I just published v0.0.15 that will not perform the input checking for the fossil cat command

**Closed by koog1000** 2019-10-19 16:19 UTC
