### ISSUE TITLE
add/remove file in a dir

### ISSUE THREAD

**Issue by vinniec** [koog1000/vscode-fossil#18] opened 2019-11-17 07:56 UTC
could you add the possibility of recursively adding/removing files in a directory?
it's a little boring to have to insert one file at a time.

**Comment by koog1000** [comment] 2019-11-17 18:14
I added a new command to add multiple files in e2a6ad2e0ea95f8a3aee1b8a4d15e69a276da118. I'll upload to VS code marketplace momentarily. You can access it by opening command palette (`Ctrl+Shift+P` on Windows) and typing `Fossil: Select Files to Add` or by right-clicking on the untracked files group in the scm panel and clicking the command from there.

Nothing for removing multiple files has been added, is this really a feature you need? I can't imagine it comes up often that you need to `fossil rm <directory>/*`

fossil itself does provide the [`addremove`](https://fossil-scm.org/index.html/help/addremove) command that I think is kind of what you're after, but I'm hesitant to add that because people who don't know what they are doing can mess up their repo with it.

**Comment by vinniec** [comment] 2019-11-17 21:01
I've tried both, with the control palette, and with the right button on the group, both work.
The problem is that you can't add all the files in a directory yet, you can select all files from you new options (that is also good) or clicking on a group and do `add all untracked files` but right-clicking on a directory shows nothing something like `tracking all files in this directory`.

It is usually not useful to remove an entire directory from tracking... unless you entered it for mistake!

According to my notes on how fossil works (yes, I have little memory), `addremove` is not what I mean (it seems that tracks all files not tracked and removes from the tracking those that no longer exist, so maybe is dangerous as you say).
What I'm referring is `add/rm` by specifying a directory as argument instead of a file (like the example you write for removing directory).

let me make a use-case:
Currently the group `Untracked files` is available (that you can see with or without directories).
When the directories are shown it would be possible for example to select a directory to add all file it contains (with the right mouse button or with a `+` icon).
And in this way the directory could end up in `changes` group as it already works, and even from here you could put the possibility to remove an entire directory from tracking in the same way (menu item or `arrow` icon).
Once the commit is done, however, it might be useful to have also a `Tracked Files` group ("fossil ls" ?) so you can decide to remove individual files or directories from the tracking.

Do you think that would be intuitive enough?

**Comment by koog1000** [comment] 2019-11-18 03:50
oooh... You're referring to the new tree view mode in the scm panel? 

Yes, that is a good feature to add. I'll have to look into it some more, I'm not sure how to use it at this exact moment.

**Comment by vinniec** [comment] 2019-11-18 06:08
I've been using vscode for a few days, I didn't know it was a new feature of the scm panel!
Thanks for the cordiality, I think there are few editors with fossil support (this is the first one I find), and so thanks also for your extension :)

**Comment by koog1000** [comment] 2019-11-23 15:32
I added file actions for the scm/resourcefolder. Tested very minimally, let me know if it works for you. v0.0.17 should be up in marketplace momentarily.

If it works correctly then please close the issue.

**Comment by koog1000** [comment] 2019-11-23 15:36
nevermind. It doesn't work as intended... I knew the change couldn't be that easy...

**Comment by vinniec** [comment] 2019-11-23 15:48
I stay in listening, when you need someone to do some testing, I am available :)

**Comment by koog1000** [comment] 2019-11-23 16:08
Ok, I think I fixed it now. v0.0.18 should be up shortly

**Comment by vinniec** [comment] 2019-11-23 17:40
Okay, that's weird. It doesn't seem to work perfectly.
There are the `+` icons on the directories (great), but pressing it seems that it insert 2 files at a time in changes (and not all files inside directory) and when I do "discard" are always canceled two files at a time from changes

**Comment by koog1000** [comment] 2019-11-23 19:00
Ha, that's funny. I only tested it with a test fossil that had two files in each folder. I'll look into it again later. There are other things I need to get done while it is light out.

**Comment by vinniec** [comment] 2019-11-23 19:42
Yes, and maybe as I told you, it can be useful to have the "tracked" section too.

**Comment by koog1000** [comment] 2019-11-24 21:40
Ok, I just updated and tested on folders with more than two files. Let me know if it works for you.

The 'tracked' group doesn't make much sense to me. If you don't need a file anymore, then you'll delete it from disk and the extension will give you the option to remove it from the repository. If you're needing to always be removing files from your repositories then you should rethink your project structure.

**Closed** 2020-02-19 05:23 UTC
Labels: enhancement
